"
" pathogen
"
call pathogen#infect()
syntax on
filetype plugin indent on

"
" various settings based on http://stevelosh.com/blog/2010/09/coming-home-to-vim/
"
set nocompatible
set modelines=0

" tabs
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

" misc
set encoding=utf-8
set autoindent
let mapleader = ","
set relativenumber
set hidden " allow unwritten buffers to be hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start " make backspace/delete work as expected
set laststatus=2
set noswapfile
set nowrap
set colorcolumn=81
set clipboard=unnamed " copy to OS copy buffer

" search
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set hlsearch
nnoremap <leader><space> :noh<cr>

"
" colors
"
colorscheme Tomorrow-Night

"
" ctrl-p
"
let ctrlp_map = '<leader>t'
nmap <leader>b :CtrlPBuffer<CR>
let g:ctrlp_dont_split = 'nerdtree'

"
" nerdtree
"
let g:NERDTreeShowLineNumbers=1
let g:NERDTreeShowHidden=1

"
" powerline
"
let g:Powerline_stl_path_style='short'

"
" vroom
"
let g:vroom_use_colors = 0
let g:vroom_use_bundle_exec = 0
let g:vroom_binstubs_path = './.binstubs'
let g:vroom_use_binstubs = 1

"
" markdown headers
"
nnoremap <leader>1 yypVr=o<Esc>o<Esc>
nnoremap <leader>2 yypVr-o<Esc>o<Esc>

"
" strip trailing whitespace
"
function! <SID>StripTrailingWhitespaces()
    " save last search, and cursor position.
    let _s=@/
    let l = line(".")
    let c = col(".")
    " strip whitespace
    %s/\s\+$//e
    " restore previous search history, and cursor position
    let @/=_s
    call cursor(l, c)
endfunction

" strip whitespace for all files on write
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

" soft wrap via :Wrap command
command! -nargs=* Wrap set wrap linebreak nolist

" save file when switch away, swallow errors
autocmd BufLeave,FocusLost * silent! wall

" remap . key in visual mode
vnoremap . :norm.<CR>

" go back to normal mode after save
" works particularly well for macvim <D-s> saves
autocmd BufWritePost * stopinsert
